### ISSUE TITLE
Desconstruir Verbo (passar pro infinitivo)

### ISSUE THREAD

**Issue by bruno222** [theuves/conjugador#1]
Fala Matheus, tudo certo?

To fazendo uma lógica de pesquisa e, uma das etapas é formatar o texto pra ter maiores chances de ser indexado. As etapas de formatação são: 

> Texo original > Tirar o acento > Remover o Plural > Colocar os verbos no infinitivo > Texto pra indexar

Daí se o texto for `amais a todos` e se alguém pesquisar por `ame`. Se ambos os textos tiverem a lógica de colocar o verbo no infinitivo, será mais acertivo.

com os verbos irregulares fica até fácil fazer, eu vi aqui seu código, é só fazer um DE-PARA inverso.

Mas e pros verbos regulares? Tens ideia de como posso fazer? Passar de `amais` pra `amar`?

Valeu amigo! Abraços.

**Comment by theuves** [comment]
Olá Bruno!

Bem, de inicio eu penso que obter o infinitivo dos verbos **regulares** será mais fácil do que dos **irregulares**, pois em verbos regulares você apenas precisará fazer mudanças no sufixo (com Expressões Regulares), enquanto nos irregulares terá que usar algum tipo de lista, assim como a que é usada por esta ferramenta (lembrando que a lista que eu uso não é completa, tendo pouco mais de 160 verbos).

Portanto obter o infinitivo dos regulares, basta substituir o sufixo pela vogal temática (*a*, *e* ou *i*) + *r*. Um exemplo de como obter o infinitivo de verbos terminado em *ar* conjugados no presente do indicativo:

```js
function infinitivo(verbo) {
  var regex = /(o|as|a|amos|ais|amam)$/;

  return verbo.replace(regex, "ar");
}

var verbo1 = infinitivo("amais");
var verbo2 = infinitivo("conversamos")
var verbo3 = infinitivo("programo");

console.log(verbo1);
console.log(verbo2);
console.log(verbo3);

// Retornaria:
// "amar"
// "conversar"
// "programar"
```

Você pode ver [aqui](https://github.com/theuves/conjugador/tree/master/src/lib/construir/terminacoes) como são as terminações dos verbos terminados em *ar*, *er* e *ir* (lá também têm dos terminados em *pôr*, lembrando que os que têm esta terminação são os únicos verbos da língua portuguesa que terminam em *or* ― não há verbos terminados em *ur*).

***

Não entendi exatamente como você quer obter o infinitivo dos irregulares.

***

**Uma pergunta**: como você fará para identificar se uma palavra no texto é realmente um verbo? Por exemplo, como fará para saber se *amas* é um verbo conjugado na segunda pessoa do singular do presente do indicativo ou se é apenas um substantivo no plural?

**Comment by bruno222** [comment]
**Verbos Regulares:** Poxa, legal demais. Entendi. Obrigado Matheus!

**Verbos irregulares**: Vou varrer esse seu [objeto aqui](https://github.com/theuves/conjugador/blob/master/src/lib/irregulares/index.json), fazendo um DE-PARA mesmo... Se a palavra for `abaúlo`, então trocar por `abaular`.

**Sobre sua pergunta** Se vier `amas`, eu vou trocar pra `amar`. Não importa se é verbo ou substantivo, uma vez que vou indexar TODAS as palavras. O projeto aqui é assim: Temos um banco de dados de FAQ (perguntas e respostas), e os usuários vão pesquisar algo dentro desse FAQ. Então vou aplicar a regra pra tirar deixar as palavras no infinitivo tanto do banco de dados como também da frase que o usuário está pesquisando... Quanto mais match (palavras iguais), melhor. 

A biblioteca que estou usando é [esta daqui](https://github.com/weixsong/elasticlunr.js) - Esta biblioteca dá pontos mesmo se as palavras forem um pouco diferentes (`amar` e `amando`), mas ela dará mais pontos se as palavras forem as mesmas, por isso estou criando a lógica de formatar o texto antes de fazer a pesquisa, só pra solução inteira ser mais acertiva...

No fim o output do que vou fazer não via pro usuário. Serve só pra indexar mesmo, Então pouca importa eu errar um pouco (como não saber a diferença entre substantivo e verbo), contanto que este erro seja aplicado nas duas fontes (no banco de dados e no que o usuário está buscando), o match vai funcionar!

De novo, obrigado pelo help, Matheus, me deu uma boa luz aqui. Valeu amigo.

**Comment by theuves** [comment]
Fico feliz em ajudá-lo.

Estou sempre livre e disposto para contribuir em qualquer coisa.

;-)

**Comment by theuves** [comment]
Uma coisa que eu não mencionei no projeto é que a lista de verbos foi obtida [neste *PDF*](http://natura.di.uminho.pt/download/sources/Dictionaries/publishing/tabVerbI.pdf). Creio que ele poderá ajudá-lo também. [Usei Expressões Regulares para montar o objeto JSON.]

***

*P.S.*: enquanto escrevia isto, encontrei também um outro *PDF* compactado [neste *ZIP*](http://natura.di.uminho.pt/download/sources/Dictionaries/publishing/tabVerb.zip) (*se clicar ele será baixado*) com um outro *PDF* maior (mais de 10MB) no qual eu creio que tenha mais verbos e conjugações em outros modos verbais. Dez megabytes é muita coisa, principalmente em uma biblioteca relativamente simples, mas talvez também seja útil.
